[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600

lib_deps =
    robtillaart/HX711@0.6.3
    adafruit/DHT sensor library@1.4.6
    waspinator/AccelStepper@^1.64
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    mathertel/OneButton @ 2.6.2
