// defines.h
/*
 * DEFINES
 * Define constants and global variables for the Alamang Mega MK3 project
 */

#include <Arduino.h>

// THESE MACRO DEFINE THE MIXER PARAMETERS
#define MOTOR_PWM_PIN 8           // THE ARDUINO MEGA PIN CONNECTED TO THE PWM PIN OF THE IBT2 MOTOR DRIVER, PIN 8 IS PWM CAPABLE.
#define MIXER_SPEED 50            // THIS DEFINE THE SPEED OF THE MIXER IN PERCENT (0-100)
#define MIXING_DURATION_MINUTES 1 // duration to run mixer after adding shrimp and salt, adjust as needed MINIMUM 1

// adjust pins if needed

#define DHT_PIN1 4
#define DHT_PIN2 5
#define DHT_TYPE DHT22

// THESE MACROS DEFINE THE PARAMETERS FOR THE LOAD CELL + HX711 FOR MEASURING WEIGHT
// SCALE_OFFSET AND SCALE_CALIBRATION_FACTOR CAN BE CALIBRATED BY SETTING THE MACRO BELOW TO TRUE AND FOLLOWING INSTRUCTION ON SERIAL MONITOR
#define TO_CALIBRATE false // set to true to run calibration routine, false to run normal operation
#define SCALE_CLK_PIN 6
#define SCALE_DAT_PIN 7
#define SCALE_OFFSET 108263
#define SCALE_CALIBRATION_FACTOR 237.015838

// THESE MACROS DEFINE THE STEPPER MOTOR DRIVER PINS CONNECTED TO THE ARDUINO MEGA
// DIR(DIRECTION) PIN IS RESPONSIBLE FOR SELECTING WHICH DIRECTION THE STEPPER MOTOR ROTATES
// PUL(PULSE) PIN IS RESPONSIBLE FOR MOVING THE STEPPER MOTOR ONE STEP AT EACH PULSE
#define STEPPER_SALT_DIR_PIN 48
#define STEPPER_SALT_PUL_PIN 49
#define STEPPER_SHRIMP_DIR_PIN 50
#define STEPPER_SHRIMP_PUL_PIN 51
#define SALT_MICROSTEPS 16   // MICROSTEP SETTING ON THE STEPPER MOTOR DIP SWITCH FOR SALT STEPPER
#define SHRIMP_MICROSTEPS 16 // MICROSTEP SETTING ON THE STEPPER MOTOR DIP SWITCH FOR SHRIMP STEPPER
#define STEPS_PER_REV 200    // STEPS PER REV OF THE STEPPER MOTOR BASED ON THE MANUFACTURER SPECIFICATIONS

// FORMULA RATIO = SALT WEIGHT / SHRIMP WEIGHT
#define RATIO .1
// THIS MACROS DEFINE THE SCREW DISPENSER ROTATION FOR EACH CYCLE
// HIGHER VALUE MEANS MORE MATERIAL IS DISPENSED EACH TIME, BUT IT MAY RESULT TO HIGHER EXCESS
// LOWER VALUE MEANS LESS MATERIAL IS DISPENSED EACH TIME AND IT MAY TAKE LONGER TO DISPENSE SPECIFIED QUANTITY
// HOWEVER, LOWER VALUE RESULTS TO LOWER EXCESS
#define SALT_ROTATE_PER_CYCLE .25
#define SHRIMP_ROTATE_PER_CYCLE .25

// THESE MACROS DEFINE THE LCD PARAMETERS
#define LCD_I2C_ADDR 0x27 // THE I2C ADDRESS OF THE LCD I2C MODULE
#define LCD_COLS 20       // THE NUMBER OF COLUMNS OF THE LCD
#define LCD_ROWS 4        // THE NUMBER OF ROWS OF THE LCD

// THESE MACROS DEFINE THE PARAMETERS FOR THE BUTTON
#define BUTTON_PIN 19        // THE ARDUINO MEGA PIN WHERE THE BUTTON IS CONNECTED, PIN D19 IS AN INTERRUPT CAPABLE PIN, A PULLDOWN RESISTOR IS CONNECTED
#define DEBOUNCE_TIME 50     // DEBOUNCE TO PREVENT MULTIPLE ACTIVATION OF THE PIN ON SINGLE CLICK OR BUTTON PRESS, A BUTTON PRESS IS USED TO START THE PROCESS WHILE ITS IDLE
#define LONG_PRESS_TIME 1000 // HOW MANY MILLISECONDS THE BUTTON NEEDS TO BE PRESSED SO THAT IT REGISTERS A LONG PRESS, LONG PRESS IS USED TO ABORT THE PROCESS ONCE IT STARTED

// THESE MACROS DEFINE THE PARAMETERS FOR THE HEATER
#define HEATER_SWITCH_PIN 18 // THE ARDUINO MEGA PIN WHERE THE TOGGLE SWITCH IS CONNECTED, PIN D18 IS ALSO AN INTERRUPT CAPABLE PIN, A PULLDOWN RESISTOR IS CONNECTED
#define HEATER_RELAY_PIN 9   // THE ARDUINO MEGA PIN WHERE THE RELAY PIN TO SWITCH THE PID TEMPERATURE CONTROLLER OF THE HEATER IS CONNECTED
